backend:
  name: github
  repo: "adilarshidin/inmaculada-concepcion"
  branch: master
  base_url: https://inmaculadavigo-oauth.onrender.com

media_folder: "content/images"

collections:
  - name: "schedule"
    label: "Horarios"
    files:
      - name: "masses"
        label: "Horarios de misas"
        file: "content/schedule/masses.md"
        fields:
          - { label: "Contenido", name: "body", widget: "markdown" }

      - name: "intentions"
        label: "Intenciones de misas"
        file: "content/schedule/intentions.md"
        fields:
          - label: "Intenciones"
            name: "intentions"
            widget: "list"
            summary: "{{fields.date}} — {{fields.name}}"
            fields:
              - { label: "Fecha", name: "date", widget: "string" }
              - { label: "Intención", name: "name", widget: "string" }
